#- name: Add the OS specific varibles
#  include_vars: "{{ ansible_os_family }}.yml"

- include: main_Debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - base

- include: main_RedHat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - base
