### timezone
- name: check timezone
  command: cat /etc/timezone
  changed_when: no
  check_mode: no
  register: check_timezone

- name: set timezone
  copy: content={{ system_timezone }}
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644
  become: yes
  when: check_timezone.stdout.find('{{ system_timezone }}') == -1
  notify:
    - update_timezone_Debian

### user
- name: create user
  user: name={{ item.user }} uid={{ item.uid }} shell={{ item.shell }}
  become: yes
  when: item.uid is defined
  with_items: "{{ user_data }}"
  tags:
    - create_user

- name: set user password
  user: name={{ item.user }} password={{ item.password | password_hash('sha512') }}
  become: yes
  changed_when: no
  with_items: "{{ user_passwords }}"
  tags:
    - create_user

- name: change default shell
  user: name={{ item.user }} shell={{ item.shell }}
  become: yes
  when: item.uid is undefined
  with_items: "{{ user_data }}"
  tags:
    - create_user
