- name: add the new GPG key for docker
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  become: yes

- name: create /etc/apt/sources.list.d/docker.list
  lineinfile:
    dest: /etc/apt/sources.list.d/docker.list
    line: "{{ docker_repo }}"
    create: yes
  become: yes

- name: apt-get update
  apt:
    update_cache: yes
  become: yes

- name: install the linux-image-extra-* packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - linux-image-extra-{{ ansible_kernel }}
    - linux-image-extra-virtual

- name: install the docker-engine
  apt:
    name: docker-engine
    state: latest
  become: yes

- name: start docker-engine
  systemd:
    name: docker
    state: started
    enabled: yes
  become: yes

- name: check if docker group exists
  shell: /usr/bin/getent group | awk -F":" '{print $1}' | egrep '^docker$'
  changed_when: no
  check_mode: no
  failed_when: check_docker_group.rc > 1
  register: check_docker_group

- name: add user in docker group
  user: name={{ ansible_ssh_user }} groups=docker append=yes
  become: yes
  when: check_docker_group.rc == 0

- name: cp pipework
  command: creates=/usr/local/bin/pipework cp -p /home/{{ ansible_ssh_user }}/.ghq/github.com/jpetazzo/pipework/pipework /usr/local/bin/
  become: yes
