- name: ntp start
  service: name=ntpd state=started enabled=yes
  become: yes

- name: upload ntp.conf
  template: src=ntp.conf_RedHat.j2 dest=/etc/ntp.conf
  become: yes
  notify: ntpd_restart_RedHat

