- hosts:
    - admin-development-vagrant_ubuntu14
    - test
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - package_ubuntu
    - common
    - dotfiles
    - git
    - peco
    - anyenv
    - ghq
    - evm
    - aws
    - ntp

- hosts:
    - admin-development-vagrant_ubuntu14
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - docker

- hosts:
    - admin-development-mac
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - homebrew
    - common_mac
    - dotfiles
    - anyenv
    - ghq
