- hosts:
    - isucon
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - package
    - common
    - dotfiles
    - peco
    - tmux
    - ntp

- hosts:
    - admin-development-vagrant_ubuntu14
    - test
    - phoply
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - package
    - common
    - dotfiles
    - git
    - peco
    - anyenv
    - ghq
    - aws
    - tmux

- hosts:
    - admin-development-vagrant_ubuntu14
    - test-development-test_ubuntu14
    - phoply-development-phoply_dev1
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    # we need autoconf 2.65 to build emacs24.4, but centos6 cannot install autoconf 2.65
    - evm

- hosts:
    - admin-development-vagrant_ubuntu14
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - docker
    - ntp

- hosts:
    - admin-development-mac
  vars_files:
    - private_vars/{{app}}.yml
    - private_vars/{{app}}-{{stage}}.yml
    - private_vars/{{app}}-{{stage}}-{{group}}.yml
    - group_vars/{{app}}.yml
    - group_vars/{{app}}-{{stage}}.yml
    - group_vars/{{app}}-{{stage}}-{{group}}.yml
  roles:
    - homebrew
    - common_mac
    - dotfiles
    - anyenv
    - ghq
    - skk
    - karabiner
    - tmux
