- hosts:
    - vagrant_ubuntu14
    - test_ubuntu14
  vars_files:
    - private_vars/{{stage}}.yml
    - group_vars/{{stage}}.yml
  roles:
    - package_ubuntu
    - common
    - dotfiles
    - git
    - peco
    - anyenv
    - ghq
    - evm
    - aws
    - ntp

- hosts: vagrant_ubuntu14
  vars_files:
    - private_vars/{{stage}}.yml
    - group_vars/{{stage}}.yml
  roles:
    - docker

- hosts: mac
  vars_files:
    - private_vars/{{stage}}.yml
    - group_vars/{{stage}}.yml
  roles:
    - homebrew
    - common_mac
    - dotfiles
    - anyenv
    - ghq
