- name: install evm
  git: repo=https://github.com/rejeep/evm.git dest=~/.evm update=no

- name: evm directory
  file: path=~/.evm/evm state=directory mode=0775

- name: check evm config path
  shell: cat ~/.evm/.config
  ignore_errors: yes
  changed_when: false
  always_run: yes
  register: evm_config

- name: evm config path
  command: ~/.evm/bin/evm config path ~/.evm/evm
  when: evm_config.stdout.find('/home/{{ user }}/.evm/evm') == -1

- name: install emacs
  command: creates=~/.evm/evm/emacs-24.4/bin/emacs ~/.evm/bin/evm install emacs-{{ item }}
  with_items: emacs_versions

- name: set emacs version
  command: ~/.evm/bin/evm use emacs-{{ emacs_version }}
  changed_when: false
