user_data:
 - user: ubuntu
   shell: /usr/bin/zsh
 - user: infra
   uid: 2000
   shell: /usr/bin/zsh
 - user: app
   uid: 2001
   shell: /usr/bin/zsh

pyenv:
  - user: ubuntu
    python_versions:
      - 2.7.11
      - 3.4.4
    python_version: 2.7.11
  - user: infra
    python_versions:
      - 2.7.11
      - 3.4.4
    python_version: 3.4.4
  - user: app
    python_versions:
      - 2.7.11
      - 3.4.4
    python_version: 3.4.4

rbenv:
  - user: ubuntu
    ruby_versions:
      - 2.2.4
    ruby_version: 2.2.4
  - user: infra
    ruby_versions:
      - 2.2.4
    ruby_version: 2.2.4
  - user: app
    ruby_versions:
      - 2.2.4
    ruby_version: 2.2.4

plenv:
  - user: ubuntu
    perl_versions:
      - 5.16.3
    perl_version: 5.16.3
  - user: infra
    perl_versions:
      - 5.16.3
    perl_version: 5.16.3
  - user: app
    perl_versions:
      - 5.16.3
    perl_version: 5.16.3

ndenv:
  - user: ubuntu
    node_versions:
      - v0.10.25
    node_version: v0.10.25
  - user: infra
    node_versions:
      - v0.10.25
    node_version: v0.10.25
  - user: app
    node_versions:
      - v0.10.25
    node_version: v0.10.25

goenv:
  - user: ubuntu
    go_versions:
      - 1.5
    go_version: 1.5
  - user: infra
    go_versions:
      - 1.5
    go_version: 1.5
  - user: app
    go_versions:
      - 1.5
    go_version: 1.5

gems:
  - user: ubuntu
    gem_list:
      - bundler
  - user: infra
    gem_list:
      - bundler
  - user: app
    gem_list:
      - bundler

python_packages:
  - user: ubuntu
    package_list:
      - ansible
      - docker-compose
  - user: infra
    package_list:
      - ansible
  - user: app
    package_list:
      - ansible

ghq_repos:
  - user: ubuntu
    repos:
      - user: yumaatt
        repo: hello_app
      - user: yumaatt
        repo: testrepo
      - user: yumaatt
        repo: dotfiles
      - user: yumaatt
        repo: ansible-playbooks
      - user: yumaatt
        repo: dockerfiles
      - user: jpetazzo
        repo: pipework
  - user: infra
    repos:
      - user: yumaatt
        repo: dotfiles
  - user: app
    repos:
      - user: yumaatt
        repo: hello_app
      - user: yumaatt
        repo: dotfiles

docker_repo: deb https://apt.dockerproject.org/repo ubuntu-xenial main
