- name: add-apt-repository
  apt_repository: repo={{ item }}
  become: yes
  with_items: apt_repository_Debian

- name: apt-get update
  apt: update_cache=yes
  become: yes

- name: apt-get install packages
  apt: pkg={{ item.name }} state={{ item.state }}
  become: yes
  with_items: packages_Debian
