apt_repository_Debian:
  - ppa:git-core/ppa

packages_Debian:
  #- { name: autoconf, state: latest }
  #- { name: automake, state: latest }
  #- { name: autogen, state: latest }
  #- { name: arping, state: latest }
  #- { name: apt-transport-https, state: latest }
  #- { name: bc, state: latest }
  #- { name: bridge-utils, state: latest }
  #- { name: build-essential, state: latest }
  #- { name: ca-certificates, state: latest }
  - { name: curl, state: latest }
  - { name: dstat, state: latest }
  - { name: emacs, state: latest }
  #- { name: exuberant-ctags, state: latest }
  #- { name: g++, state: latest }
  #- { name: gcc, state: latest }
  - { name: git, state: latest }
  #- { name: install-info, state: latest }
  - { name: jq, state: latest }
  #- { name: libsqlite3-dev, state: latest }
  #- { name: libffi-dev, state: latest }
  #- { name: libssl-dev, state: latest }
  - { name: libreadline-dev, state: latest }
  #- { name: libbz2-dev, state: latest }
  #- { name: libsqlite3-dev, state: latest }
  #- { name: libx11-dev, state: latest }
  #- { name: libxpm-dev, state: latest }
  #- { name: libjpeg-dev, state: latest }
  #- { name: libpng12-dev, state: latest }
  #- { name: libgif-dev, state: latest }
  #- { name: libtiff5-dev, state: latest }
  #- { name: libgtk2.0-dev, state: latest }
  - { name: make, state: latest }
  #- { name: nkf, state: latest }
  #- { name: ntp, state: latest }
  #- { name: ntpdate, state: latest }
  #- { name: nginx, state: latest }
  - { name: percona-toolkit, state: latest }
  - { name: redis-server, state: latest }
  - { name: silversearcher-ag, state: latest }
  #- { name: sshpass, state: latest }
  #- { name: stone, state: latest }
  #- { name: software-properties-common, state: latest }
  - { name: texinfo, state: latest }
  - { name: tmux, state: latest }
  - { name: unzip, state: latest }
  - { name: vim, state: latest }
  #- { name: zlib1g-dev, state: latest }
  - { name: zsh, state: latest }

packages_rpm_RedHat:
  #- { name: 'http://swiftsignal.com/packages/centos/6/x86_64/the-silver-searcher-0.14-1.el6.x86_64.rpm', state: present }
  #- { name: 'http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm', state: present }

packages_RedHat:
  - { name: '@Development tools', state: latest }
  - { name: atk-devel, state: latest }
  - { name: autoconf, state: latest }
  - { name: automake, state: latest }
  - { name: curl, state: latest }
  - { name: dstat, state: latest }
  - { name: emacs, state: latest }
  - { name: git, state: latest }
  - { name: jq, state: latest }
  - { name: make, state: latest }
  - { name: redis, state: latest }
  - { name: readline, state: latest }
  - { name: readline-devel, state: latest }
  - { name: texinfo, state: latest }
  - { name: tmux, state: latest }
  - { name: unzip, state: latest }
  - { name: wget, state: latest }
  - { name: vim, state: latest }
  - { name: zsh, state: latest }
